name: anzar
description: "Streamline app development with anzar: clean architecture, dev/prod environments, and essential packages. Elevate your projects effortlessly."
publish_to: 'none'

version: 0.5.1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  logger: ^2.2.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1
  freezed: ^2.4.7
  http_interceptor: ^2.0.0-beta.8
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.8.1
  go_router: ^13.2.1
  easy_localization: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - lib/core/translations/
